(function segurosRuntime() {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const YEAR = new Date().getFullYear();
  const TASAS_AUTO = {
    mx:{basico:[.8,1.5],intermedio:[2,3.5],amplio:[3.5,6.5]}, gt:{basico:[1.2,2],intermedio:[2,3.5],amplio:[2.5,5]},
    sv:{basico:[.8,1.5],intermedio:[1.5,2.8],amplio:[2.2,4]}, hn:{basico:[1.5,2.5],intermedio:[2.5,4],amplio:[3.5,6]},
    ni:{basico:[1.5,2.5],intermedio:[2.5,4],amplio:[3,5.5]}, cr:{basico:[.8,1.5],intermedio:[1.5,2.5],amplio:[2,4]},
    pa:{basico:[.6,1.1],intermedio:[1.2,2],amplio:[2,3.8]}
  };
  const SALUD_USD_MENSUAL_35 = { mx:[217,371], gt:[103,258], sv:[80,220], hn:[99,217], ni:[41,110], cr:[59,157], pa:[130,250] };
  const DEFAULT_AUTO_VALOR = { cr:12000000, mx:350000, gt:120000, sv:20000, hn:500000, ni:15000, pa:20000 };
  const els = {
    pais:$('pais'), countryPill:$('insurance-country-pill'), results:$('insurance-results'), sort:$('insurance-sort'),
    tabs:Array.from(document.querySelectorAll('.insurance-tab')), fields:Array.from(document.querySelectorAll('[data-insurance-fields]')),
    autoValor:$('ins-auto-valor'), autoValorLabel:$('ins-auto-valor-label'), autoAnio:$('ins-auto-anio'), autoAnioLabel:$('ins-auto-anio-label'),
    autoCobertura:$('ins-auto-cobertura'), autoUso:$('ins-auto-uso'), autoZona:$('ins-auto-zona'), autoEdad:$('ins-auto-edad'), autoEdadLabel:$('ins-auto-edad-label'),
    vidaEdad:$('ins-vida-edad'), vidaEdadLabel:$('ins-vida-edad-label'), vidaSuma:$('ins-vida-suma'), vidaSumaLabel:$('ins-vida-suma-label'), vidaFumador:$('ins-vida-fumador'), vidaPlazo:$('ins-vida-plazo'),
    saludEdad:$('ins-salud-edad'), saludEdadLabel:$('ins-salud-edad-label'), saludPlan:$('ins-salud-plan'), saludDeducible:$('ins-salud-deducible'), saludModalidad:$('ins-salud-modalidad'), saludRed:$('ins-salud-red')
  };
  let tipoActivo = 'auto';
  let usuarioEditoAutoValor = false;
  function paisId(){ return els.pais?.value || document.documentElement.dataset.pais || 'cr'; }
  function pais(){ const ps = typeof PAISES !== 'undefined' ? PAISES : []; return ps.find(p => p.id === paisId()) || ps[0] || {id:'cr',nombre:'Costa Rica',moneda:'CRC',simbolo:'₡',cambioUSD:510}; }
  function moneda(){ const p = pais(); return {codigo:p.moneda === 'USD/PAB' ? 'USD' : p.moneda, simbolo:p.simbolo || '$', cambioUSD:p.cambioUSD || 1}; }
  function fmt(v, m = moneda()){ return `${m.simbolo}${new Intl.NumberFormat('es-CR',{maximumFractionDigits:0}).format(Math.max(0, Math.round(Number(v) || 0)))}`; }
  function toLocal(usd){ const m = moneda(); return m.codigo === 'USD' ? usd : usd * m.cambioUSD; }
  function clamp(n,min,max){ return Math.min(max, Math.max(min, Number(n) || 0)); }
  function aseguradoras(){ const data = typeof ASEGURADORAS !== 'undefined' ? ASEGURADORAS : []; return data.filter(a => a.pais === paisId() && a.productos?.[tipoActivo]); }
  function factorAntiguedad(anio){ const e = Math.max(0, YEAR - anio); if(e > 15) return .78; if(e > 10) return .85; if(e > 5) return .92; if(e <= 1) return 1.04; return 1; }
  function factorEdad(edad){ if(edad < 25) return 1.22; if(edad > 70) return 1.12; if(edad > 60) return 1.06; return 1; }
  function factorUso(uso){ return uso === 'plataforma' ? 1.6 : uso === 'comercial' ? 1.35 : 1; }
  function factorZona(zona){ return zona === 'alto_riesgo' ? 1.28 : zona === 'capital' ? 1.12 : .96; }
  function coberturaLabel(v){ return {basico:'Básica', intermedio:'Intermedia', amplio:'Todo riesgo'}[v] || v; }
  function precisionAuto(){ const edad = Number(els.autoEdad.value || 35); return (els.autoUso.value !== 'particular' || els.autoZona.value === 'alto_riesgo' || edad < 25) ? 'Media-alta' : 'Alta'; }
  function build(a,min,max,meta){ const monthlyMin = meta.frecuencia === 'mensual' ? min : min/12; const monthlyMax = meta.frecuencia === 'mensual' ? max : max/12; return {aseguradora:a,min:Math.round(min),max:Math.round(max),monthlyMin:Math.round(monthlyMin),monthlyMax:Math.round(monthlyMax),meta,cotizador:a.productos[tipoActivo].cotizador || a.web,nota:a.productos[tipoActivo].nota || 'Precio final sujeto a evaluación oficial.'}; }
  function calcAuto(a){ const valor=clamp(els.autoValor.value,1000,999999999), anio=clamp(els.autoAnio.value,1990,YEAR+1), cobertura=els.autoCobertura.value; const tasas=(TASAS_AUTO[paisId()]||TASAS_AUTO.cr)[cobertura]||TASAS_AUTO.cr.amplio; const factor=factorAntiguedad(anio)*factorEdad(clamp(els.autoEdad.value,18,85))*factorUso(els.autoUso.value)*factorZona(els.autoZona.value)*(a.productos.auto.factor||1); return build(a,valor*(tasas[0]/100)*factor,valor*(tasas[1]/100)*factor,{frecuencia:'anual',productoLabel:'Seguro de auto',detalle:`${coberturaLabel(cobertura)} · ${anio} · ${els.autoUso.options[els.autoUso.selectedIndex].text}`,variables:['valor del vehículo','año','cobertura','zona','edad del conductor','uso'],precision:precisionAuto()}); }
  function tarifaVida(edad){ if(edad <= 30) return [15,25]; if(edad <= 40) return [25,45]; if(edad <= 50) return [60,110]; return [140,250]; }
  function calcVida(a){ const edad=clamp(els.vidaEdad.value,18,75), suma=clamp(els.vidaSuma.value,5000,2000000), base=tarifaVida(edad); const factor=(suma/50000)*(els.vidaFumador.value === 'si' ? 1.45 : 1)*(Number(els.vidaPlazo.value) <= 10 ? .9 : Number(els.vidaPlazo.value) >= 30 ? 1.16 : 1)*(a.productos.vida.factor||1); return build(a,toLocal(base[0]*factor),toLocal(base[1]*factor),{frecuencia:'mensual',productoLabel:'Seguro de vida',detalle:`$${new Intl.NumberFormat('es-CR').format(suma)} suma · ${els.vidaPlazo.value} años · ${els.vidaFumador.options[els.vidaFumador.selectedIndex].text}`,variables:['edad','suma asegurada','fumador','plazo'],precision:edad>55?'Media':'Alta'}); }
  function calcSalud(a){ const edad=clamp(els.saludEdad.value,0,80), base=SALUD_USD_MENSUAL_35[paisId()]||SALUD_USD_MENSUAL_35.cr; const age=edad>=35?1+((edad-35)*.06):Math.max(.55,1-((35-edad)*.025)); const factor=age*({basico:.72,intermedio:1,premium:1.58}[els.saludPlan.value]||1)*({bajo:1.18,medio:1,alto:.82}[els.saludDeducible.value]||1)*(els.saludModalidad.value==='familiar'?2.18:1)*({local:1,regional:1.18,internacional:1.45}[els.saludRed.value]||1)*(a.productos.salud.factor||1); return build(a,toLocal(base[0]*factor),toLocal(base[1]*factor),{frecuencia:'mensual',productoLabel:'Seguro de salud',detalle:`${els.saludPlan.options[els.saludPlan.selectedIndex].text} · ${els.saludModalidad.options[els.saludModalidad.selectedIndex].text} · red ${els.saludRed.options[els.saludRed.selectedIndex].text.toLowerCase()}`,variables:['edad','nivel de plan','deducible','modalidad','red médica'],precision:els.saludRed.value==='internacional'?'Media':'Media-alta'}); }
  function calcular(){ return aseguradoras().map(a => tipoActivo === 'auto' ? calcAuto(a) : tipoActivo === 'vida' ? calcVida(a) : calcSalud(a)); }
  function renderLabels(){ const m=moneda(); if(els.countryPill) els.countryPill.textContent=`${pais().nombre} · ${m.codigo}`; if(els.autoValorLabel) els.autoValorLabel.textContent=fmt(els.autoValor.value,m); if(els.autoAnioLabel) els.autoAnioLabel.textContent=`${els.autoAnio.value || YEAR}`; if(els.autoEdadLabel) els.autoEdadLabel.textContent=`${els.autoEdad.value || 35} años`; if(els.vidaEdadLabel) els.vidaEdadLabel.textContent=`${els.vidaEdad.value || 35} años`; if(els.vidaSumaLabel) els.vidaSumaLabel.textContent=`$${new Intl.NumberFormat('es-CR').format(Number(els.vidaSuma.value || 0))}`; if(els.saludEdadLabel) els.saludEdadLabel.textContent=`${els.saludEdad.value || 35} años`; }
  function render(){ renderLabels(); let results=calcular(); results.sort((els.sort?.value||'precio') === 'rating' ? (a,b)=>(b.aseguradora.rating||0)-(a.aseguradora.rating||0) : (a,b)=>a.monthlyMin-b.monthlyMin); if(!results.length){ els.results.innerHTML=`<div class="market-pending-card"><div class="market-pending-flag">${pais().bandera||''}</div><div><strong>No hay aseguradoras cargadas para este producto</strong><p>Estamos validando fuentes y cotizadores oficiales para ${pais().nombre}. Probá con otro tipo de seguro o país.</p></div></div>`; return; } const bestPrice=Math.min(...results.map(r=>r.monthlyMin)), bestRating=Math.max(...results.map(r=>r.aseguradora.rating||0)), m=moneda(); els.results.innerHTML=results.map(r=>{ const isBestPrice=r.monthlyMin===bestPrice, isBestRating=(r.aseguradora.rating||0)===bestRating; const labelRange=r.meta.frecuencia==='mensual'?`${fmt(r.min,m)} - ${fmt(r.max,m)} / mes`:`${fmt(r.min,m)} - ${fmt(r.max,m)} / año`; return `<article class="insurance-result ${isBestPrice?'best':''}"><div class="insurance-result-main"><div class="bank-card-info"><div class="bank-logo" style="background:${r.aseguradora.color};">${r.aseguradora.iniciales}</div><div class="bank-card-info-text"><div class="bank-card-name">${r.aseguradora.nombre}</div><div class="bank-card-meta">${r.aseguradora.tipo} · ${r.meta.productoLabel} · ${r.meta.precision} precisión</div></div></div><div class="insurance-badges">${isBestPrice?'<span class="insurance-badge badge-price">Mejor precio estimado</span>':''}${isBestRating?'<span class="insurance-badge">Mejor rating</span>':''}</div></div><div class="insurance-result-metrics"><div><span>Prima estimada</span><strong>${labelRange}</strong></div><div><span>Desde</span><strong>${fmt(r.monthlyMin,m)} / mes</strong></div><div><span>Perfil</span><strong>${r.meta.detalle}</strong></div></div><details class="insurance-details"><summary>Ver detalles</summary><div class="insurance-detail-body"><p><strong>Variables usadas:</strong> ${r.meta.variables.join(', ')}.</p><p>${r.nota}</p><p>Este rango se ajusta por país, tipo de cobertura, perfil y factor referencial de aseguradora. La prima exacta depende de sus tablas actuariales, historial, zona y evaluación final.</p></div></details><div class="insurance-result-actions"><a href="${r.cotizador}" target="_blank" rel="noopener" class="btn-detail">Cotizar exacto</a></div></article>`; }).join(''); }
  function setTipo(next){ tipoActivo=next; els.tabs.forEach(t=>t.classList.toggle('active',t.dataset.insuranceType===next)); els.fields.forEach(g=>{ g.hidden = g.dataset.insuranceFields !== next; }); render(); }
  function syncCountry(force=false){ if(els.autoValor && (force || !usuarioEditoAutoValor)) els.autoValor.value=DEFAULT_AUTO_VALOR[paisId()]||DEFAULT_AUTO_VALOR.cr; render(); }
  function init(){ if(!els.results) return; els.tabs.forEach(t=>t.addEventListener('click',()=>setTipo(t.dataset.insuranceType))); document.querySelectorAll('#insurance-form input, #insurance-form select').forEach(i=>i.addEventListener('input',render)); document.querySelectorAll('#insurance-form select').forEach(i=>i.addEventListener('change',render)); els.sort?.addEventListener('change',render); els.autoValor?.addEventListener('input',()=>{ usuarioEditoAutoValor=true; }); els.pais?.addEventListener('change',()=>syncCountry(true)); els.pais?.addEventListener('input',()=>syncCountry(true)); syncCountry(false); }
  if(document.readyState === 'loading') document.addEventListener('DOMContentLoaded',init); else init();
})();